# Generated by Django 3.2.2 on 2021-05-15 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_todo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['status', '-pk']},
        ),
    ]
